version: '3'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
    - 5432
    volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data
    # copy the sql script to create tables
    - ./volumes/postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
