version: '3'
services:
  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
    - 5432:5432
    volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data
    - ./volumes/postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  epaper:
    build: ../
    container_name: epaper
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - 8080:8080
    depends_on:
      - postgres
networks:
  epaper:
    ipam:
      driver: default
