package com.example.epaper.service;

import com.example.epaper.xsd.Epaper;

import javax.xml.bind.JAXBException;
import java.io.ByteArrayInputStream;

/**
 * Service for parsing xml files over xsd schema structure
 */
public interface JaxbParseService {

    /**
     * Reads data from XML file
     *
     * @param inputStream represents file's content
     * @return model, generated by xsd with content from parsed file
     * @throws JAXBException in of errors while parsing
     */
    Epaper parseFromFile(final ByteArrayInputStream inputStream) throws JAXBException;

    /**
     * Validates content of file over xsd schema
     *
     * @param inputStream represents file's content
     */
    void validate(final ByteArrayInputStream inputStream);

}
