CREATE TABLE IF NOT EXISTS NEWSPAPER (
  ID SERIAL,
  NEWSPAPER_NAME varchar(200) NOT NULL,
  DEVICE_WIDTH INT,
  DEVICE_HEIGHT INT,
  DEVICE_DPI INT,
  UPLOAD_TIME TIMESTAMP,
  FILENAME varchar(200) NOT NULL,
  PRIMARY KEY (id)
);
